version: "3.9"

configs:
  nginx_conf:
    file: ./nginx.conf

networks:
  bookora-net:
    driver: overlay

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:6
    volumes:
      - mongo_data:/data/db
    networks:
      - bookora-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager  # demo single-node; production hãy gắn label cho node lưu dữ liệu

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks:
      - bookora-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: bookora-backend:latest   # build trước local image
    env_file:
      - ./backend/.env.pro
    environment:
      MONGODB_URI: mongodb://mongo:27017/bookora
      REDIS_HOST: redis
      PORT: "4000"
    networks:
      - bookora-net
    deploy:
      replicas: 3                   # scale mặc định 3 replicas
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
    # Không publish port; Swarm VIP + Nginx sẽ proxy

  mail-service:
    image: bookora-mail-service:latest
    env_file:
      - ./mail-service/.env.pro
    environment:
      REDIS_HOST: redis
      PORT: "4001"
    networks:
      - bookora-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: bookora-frontend:latest
    env_file:
      - ./frontend/.env.pro
    environment:
      # Nếu frontend cần gọi backend, đặt API_URL trỏ tới http://backend:4000 (Swarm DNS)
      NEXT_PUBLIC_API_URL: http://backend:4000
      PORT: "3000"
    networks:
      - bookora-net
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 4000
        protocol: tcp
        mode: ingress
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - bookora-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure